apiVersion: v1
kind: Service
metadata:
  name: expense.tracker-service
spec:
  type: LoadBalancer
  selector:
    app: expense.tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
